//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinedSpendatures
    {
        public int SpendatureId { get; set; }
        public string StoreName { get; set; }
        public string StoreTypeName { get; set; }
        public decimal AmountSpent { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string SpendatureTypeName { get; set; }
    }
}
