//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyBudgetEntities : DbContext
    {
        public MyBudgetEntities()
            : base("name=MyBudgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<Spendature> Spendature { get; set; }
        public virtual DbSet<SpendatureType> SpendatureType { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<StoreType> StoreType { get; set; }
        public virtual DbSet<DefinedSpendatures> DefinedSpendatures { get; set; }
    }
}
